appname = casdoor
httpport = 8000
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = postgres
dataSourceName = user=casdoor password=casdoor host=postgres port=5432 dbname=casdoor sslmode=disable
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = casdoor
socks5Proxy =
verificationCodeTimeout = 10
initScore = 2000
logPostOnly = true
origin = http://localhost:9000
staticBaseUrl = https://cdn.casbin.org
isDemoMode = false
batchSize = 100
enableGzip = true
initDataFile = ./init_data.json
initDataNewOnly = false
