services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: cmn-keycloak
    platform: ${DOCKER_PLATFORM:-linux/arm64}
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    volumes:
      - ./etc/keycloak:/opt/keycloak/data/import:ro
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - cmn-network
    dns:
      - 10.88.0.53
    restart: unless-stopped
